export const nationalities = [
    "Portugal",
    "",
    "Afeganistão",
    "África do Sul",
    "Albânia",
    "Alemanha",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antártida",
    "Antígua e Barbuda",
    "Arábia Saudita",
    "Argélia",
    "Argentina",
    "Armênia",
    "Aruba",
    "Austrália",
    "Áustria",
    "Azerbaijão",
    "Bahamas",
    "Bahrein",
    "Bangladesh",
    "Barbados",
    "Bélgica",
    "Belize",
    "Benin",
    "Bermudas",
    "Bielorrússia",
    "Bolívia",
    "Bósnia e Herzegovina",
    "Botswana",
    "Brasil",
    "Brunei",
    "Bulgária",
    "Burkina Faso",
    "Burundi",
    "Butão",
    "Cabo Verde",
    "Camarões",
    "Camboja",
    "Canadá",
    "Catar",
    "Cazaquistão",
    "Chade",
    "Chile",
    "China",
    "Chipre",
    "Colômbia",
    "Comores",
    "Congo",
    "Costa do Marfim",
    "Costa Rica",
    "Croácia",
    "Cuba",
    "Dinamarca",
    "Djibouti",
    "Dominica",
    "Egito",
    "El Salvador",
    "Emirados Árabes Unidos",
    "Equador",
    "Eritreia",
    "Escócia",
    "Eslováquia",
    "Eslovênia",
    "Espanha",
    "Estados Unidos",
    "Estônia",
    "Eswatini",
    "Etiópia",
    "Fiji",
    "Filipinas",
    "Finlândia",
    "França",
    "Gabão",
    "Gâmbia",
    "Gana",
    "Geórgia",
    "Gibraltar",
    "Granada",
    "Grécia",
    "Groenlândia",
    "Guadalupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guiana",
    "Guiana Francesa",
    "Guiné",
    "Guiné Equatorial",
    "Guiné-Bissau",
    "Haiti",
    "Holanda",
    "Honduras",
    "Hong Kong",
    "Hungria",
    "Iêmen",
    "Ilha Bouvet",
    "Ilha do Homem",
    "Ilha Natal",
    "Ilha Pitcairn",
    "Ilhas Aland",
    "Ilhas Cayman",
    "Ilhas Cocos",
    "Ilhas Cook",
    "Ilhas Faroe",
    "Ilhas Geórgia do Sul e Sandwich do Sul",
    "Ilhas Heard e McDonald",
    "Ilhas Malvinas",
    "Ilhas Marianas do Norte",
    "Ilhas Marshall",
    "Ilhas Menores Distantes dos EUA",
    "Ilhas Norfolk",
    "Ilhas Turks e Caicos",
    "Ilhas Virgens Americanas",
    "Ilhas Virgens Britânicas",
    "Índia",
    "Indonésia",
    "Inglaterra",
    "Irã",
    "Iraque",
    "Irlanda",
    "Irlanda do Norte",
    "Islândia",
    "Israel",
    "Itália",
    "Jamaica",
    "Japão",
    "Jersey",
    "Jordânia",
    "Kuwait",
    "Laos",
    "Lesoto",
    "Letônia",
    "Líbano",
    "Libéria",
    "Líbia",
    "Liechtenstein",
    "Lituânia",
    "Luxemburgo",
    "Macau",
    "Macedônia do Norte",
    "Madagascar",
    "Malásia",
    "Malawi",
    "Maldivas",
    "Mali",
    "Malta",
    "Marrocos",
    "Martinica",
    "Maurício",
    "Mauritânia",
    "Mayotte",
    "México",
    "Mônaco",
    "Mongólia",
    "Montenegro",
    "Montserrat",
    "Moçambique",
    "Myanmar",
    "Namíbia",
    "Nauru",
    "Nepal",
    "Nicarágua",
    "Níger",
    "Nigéria",
    "Niue",
    "Noruega",
    "Nova Caledônia",
    "Nova Zelândia",
    "Omã",
    "Outros",
    "País de Gales",
    "Palau",
    "Panamá",
    "Papua-Nova Guiné",
    "Paquistão",
    "Paraguai",
    "Peru",
    "Polinésia Francesa",
    "Polônia",
    "Porto Rico",
    "Quênia",
    "Quirguistão",
    "Reino Unido",
    "República Centro-Africana",
    "República Checa",
    "República Democrática do Congo",
    "República Dominicana",
    "Reunião",
    "Romênia",
    "Ruanda",
    "Rússia",
    "Saara Ocidental",
    "Samoa",
    "Samoa Americana",
    "Santa Helena",
    "Santa Lúcia",
    "São Bartolomeu",
    "São Cristóvão e Nevis",
    "São Martinho",
    "São Martinho do Sul",
    "São Pedro e Miquelon",
    "São Tomé e Príncipe",
    "São Vicente e Granadinas",
    "Senegal",
    "Serra Leoa",
    "Sérvia",
    "Singapura",
    "Síria",
    "Somália",
    "Sri Lanka",
    "St. Martin",
    "Suécia",
    "Suíça",
    "Sudão",
    "Sudão do Sul",
    "Suriname",
    "Tailândia",
    "Taiwan",
    "Tajiquistão",
    "Tanzânia",
    "Terras Austrais e Antárticas Francesas",
    "Território Britânico do Oceano Índico",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad e Tobago",
    "Tunísia",
    "Turquemenistão",
    "Turquia",
    "Tuvalu",
    "Ucrânia",
    "Uganda",
    "Uruguai",
    "Uzbequistão",
    "Vanuatu",
    "Vaticano",
    "Venezuela",
    "Vietnã",
    "Wallis e Futuna",
    "Zâmbia",
    "Zimbábue",
  ];