// Define as seleções de modo de verificação
export const verifyModeOptions = [
    { value: 0, label: "Detetar Automaticamente" },
    { value: 1, label: "Somente Digital" },
    { value: 2, label: "ID Utilizador" },
    { value: 3, label: "Somente Password" },
    { value: 4, label: "Somente Cartão" },
    { value: 5, label: "Digital ou Password" },
    { value: 6, label: "Digital ou Cartão" },
    { value: 7, label: "Cartão ou Password" },
    { value: 8, label: "ID Utilizador + Digital" },
    { value: 9, label: "Digital + Password" },
    { value: 10, label: "Cartão + Password" },
    { value: 11, label: "Cartão + Password" },
    { value: 12, label: "Digital + Password + Cartão" },
    { value: 13, label: "ID Utilizador + Digital + Password" },
    { value: 14, label: "ID Utilizador + Digital ou Cartão + Password" },
    { value: 15, label: "Face" },
    { value: 16, label: "Face + Digital" },
    { value: 17, label: "Face + Password" },
    { value: 18, label: "Face + Cartão" },
    { value: 19, label: "Face + Digital + Cartão" },
    { value: 20, label: "Face + Digital + Password" },
    { value: 21, label: "Veia Digital" },
    { value: 22, label: "Veia Digital + Password" },
    { value: 23, label: "Veia Digital + Cartão" },
    { value: 24, label: "Veia Digital + Password + Cartão" },
    { value: 25, label: "Palma" },
    { value: 26, label: "Palma + Cartão" },
    { value: 27, label: "Palma + Face" },
    { value: 28, label: "Palma + Digital" },
    { value: 29, label: "Palma + Digital + Face" },
    { value: 200, label: "Outros" },
  ];